version: "3.9"

services:
  # ---------- FRONTEND ----------
  frontend:
    build:
      context: ./Bejitetest
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bejite-network

  # ---------- BACKEND ----------
  backend:
    build:
      context: ./Bejite_UX_2025
      dockerfile: Dockerfile
      target: prod
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/bejite
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - bejite-network

  # ---------- DATABASE ----------
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bejite
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bejite-network

# ---------- VOLUMES ----------
volumes:
  db_data:

# ---------- NETWORKS ----------
networks:
  bejite-network:
    driver: bridge
