name: DevOps CI

on:
  push:
    branches:
      - main
      - docker-compose-setup
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 🛠️ Build Full Stack
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout this DevOps repo
      - name: Checkout DevOps repository
        uses: actions/checkout@v4

      # 2️⃣ Clone the frontend repo
      - name: Clone frontend repository
        run: |
          git clone https://github.com/Elilaw179/bejitetest.git ./Bejitetest

      # 3️⃣ Clone the backend repo
      - name: Clone backend repository
        run: |
          git clone https://github.com/solprogroup/Bejite_UX_2025.git ./Bejite_UX_2025

      # 4️⃣ Set up Docker Buildx (for multi-stage builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5️⃣ Build and start the containers (backend uses 'prod' stage)
      - name: Build and run Docker Compose
        run: |
          docker compose -f docker-compose.ci.yml up --build -d

      # 6️⃣ Check running containers
      - name: Verify containers are running
        run: docker ps

      # 7️⃣ Optional: Log backend container output (for debugging)
      - name: Show backend logs
        run: docker logs $(docker ps -qf "name=backend")

      # 8️⃣ Shut down containers after build
      - name: Shut down containers
        if: always()
        run: docker compose -f docker-compose.ci.yml down -v
