name: DevOps CI - Full Stack Integration

on:
  push:
    branches:
      - docker-compose-setup   # ✅ Only trigger for your current working branch

jobs:
  fullstack-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify docker-compose file exists
        run: ls -l

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run Docker Compose
        run: docker compose -f docker-compose.yml up --build -d

      - name: Verify running containers
        run: docker ps -a

      - name: Tear down environment
        if: always()
        run: docker compose -f docker-compose.yml down
