name: Frontend CI

on:
  push:
    branches: [ "*" ]   # run on any branch
  pull_request:
    branches: [ "*" ]   # run on PRs from any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DevOps repo
        uses: actions/checkout@v4

      - name: Checkout Frontend repo
        uses: actions/checkout@v4
        with:
          repository: Ochaworldwide/Bejite
          path: frontend

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build project
        working-directory: frontend
        run: npm run build

      - name: Debug step
        run: echo "Pipeline is running on branch ${{ github.ref_name }}"

      - name: Lint code
        working-directory: frontend
        run: npm run lint || true

